### PR TITLE
Make minesweeper work on every platform 

### LINKED ISSUE #422: Minesweeper issue
## Description
Two issues, one: The top row of the XY board on iOS is broken, and two: I lost on my first move, which doesn’t happen in normal Minesweeper.

## Steps to Reproduce
Play Minesweeper on iOS

## Expected Behaviour
I expected normal letters on the top row and to not die on the first move.

## Actual Behaviour
The top row was bugged and I lost on my first move. 

## Known Impacted Platforms

- [ ] Web
- [ ] Desktop
- [ ] Android App
- [x] iOS App

## Possible Solutions
Use Unicode emojis from iOS devices, and change the loading behavior of the board to load after the first move. 

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [ ] I'd like to implement the bug fix
- [x] Anyone can implement the bug fix

C60A348A-EAA7-48B7-9DD1-E7BBE48598BC

### PR DESCRIPTION
**Pull request by algo-1**
modify code to work on all platforms,
fix grammatical errors

## Relevant Issues
Closes #422 

## Description
I added spaces between the letters at the top of the board, 
I changed "Here's there board" to "Here's *their* board"

## Reasoning
The spaces ensured that the top characters on the board looked as expected on ios devices 
The grammar fix aids better understanding of the bot's message 

## Screenshots
iphone 8 demo of change to the board 

image

## Did you:
- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)? using flake8 & precommit
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by kosayoda — CHANGES_REQUESTED** [review]
Hello and thank you for the pull request.

`flake8` should be and is a development package, and therefore is not needed under `[packages]` in the Pipfile.

**Comment by algo-1** [comment]
> Hello and thank you for the pull request.
> 
> `flake8` should be and is a development package, and therefore is not needed under `[packages]` in the Pipfile.

Should I revert all the changes made to Pipfile and Pipfile.lock? Or just remove flake8 from Pipfile, thanks

**Comment by Akarys42** [comment]
> Should I revert all the changes made to Pipfile and Pipfile.lock? Or just remove flake8 from Pipfile, thanks
Yes, it would be better if you can revert those and sync your pipenv environment using `pipenv sync --dev`. 🙂

**Comment by algo-1** [comment]
I think everything is set now @Akarys42 @kosayoda

**Review by thomaspet — APPROVED** [review]
These changes look good to me. Haven't tasted the format on my devices though.

**Review by Den4200 — APPROVED** [review]
Looks good to me - tested on iOS and desktop. Thanks!

**Pull request merged**
