### PR TITLE
remove duplicate winners for .riddle

### LINKED ISSUE #498: Same winner getting repeated when correct answer sent multiple times (.riddle)
## Description

With the `.riddle` command, when a user sends a correct answer multiple times (probably because there isn't any response immediately after correct answer), the final 'who wins' message becomes like this:
image
🔗 [message link](https://discord.com/channels/267624335836053506/607247579608121354/764406560029147146)

## Steps to Reproduce

1. go to #seasonalbot-commands
2. type `.riddle` and hit enter
3. send the correct answer multiple times
4. wait for the final message to appear

## Expected Behaviour

the mention of the user(s) who gets it correct only once

## Actual Behaviour

user mentioned multiple times (see screenshot above, or [this message link](https://discord.com/channels/267624335836053506/607247579608121354/764406560029147146))

## Possible Solutions

With `self.winners` either make it a set and update using `self.winners.add()`, or use `self.winners = list(set(self.winners))` on the last line
https://github.com/python-discord/seasonalbot/blob/ba6536cf2011dc52d1e103407d75aa699975656b/bot/exts/easter/easter_riddle.py#L86-L95

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

I'd like to implement the bug fix

### PR DESCRIPTION
**Pull request by hedythedev**
## Relevant Issues

closes #498 

## Description

`self.winners` is now a set, and when updating, `add()` will be called, and `clear()` will be called when it needs to be cleared

## Screenshots

before/after

image
image

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by thomaspet** [comment]
Instead of hotfixing the issue at the end, can we instead fix it at it's roots. In this case, make self.winners a set to begin with. and change the add methods / reset methods. That way we don't have to iterate over it at the end

**Comment by hedythedev** [comment]
@thomaspet done

**Review by thomaspet — APPROVED** [review]
Seems good to me

**Review by kwzrd — APPROVED** [review]
Good fix, thanks.

**Pull request merged**
