### PR TITLE
Bump Python version to 3.8

### LINKED ISSUE #372: Upgrade Seasonalbot to Python 3.8
With `bot` and `snekbox` now being bumped to 3.8, we should also look into bumping Seasonalbot.

This is a fairly self-explanatory issue.

As explained in https://github.com/python-discord/bot/issues/758, one of the motivations for upgrading were the improvements to unittesting asynchronous code. We do not have a testing suite for Seasonalbot, which means that we won't benefit from those improvements here, but it also means that we can more or less expect everything to work out-of-the-box, perhaps with minimal adjustments.

I would be happy to look into this myself.

Although I'm currently working on #329, I think this should probably be a separate PR.

### PR DESCRIPTION
**Pull request by kwzrd**
This PR essentially replicates the efforts of https://github.com/python-discord/bot/pull/783.

Bumps Python to 3.8 in Pipfile & lock, Azure and Docker.
Bumps the Ubuntu image in CI to 18.04.

So far it appears that Seasonalbot is fully compatible with 3.8 (tested on 3.8.2) as is, without any required adjustments. I will test some more tomorrow before taking this out of draft status.

Closes #372

### CODE REVIEW

**Comment by kwzrd** [comment]
All seasons load fine, works under Docker too.

Can't really think of anything else to test, so I'm opening this for review.

**Comment by kwzrd** [comment]
@SebastiaanZ I requested your review specifically because you handled the migration for `bot`, so there may still be some things fresh in memory that had to be adjusted, but I'm fairly sure they're more or less irrelevant for Seasonalbot.

**Comment by SebastiaanZ** [comment]
> @SebastiaanZ I requested your review specifically because you handled the migration for `bot`, so there may still be some things fresh in memory that had to be adjusted, but I'm fairly sure they're more or less irrelevant for Seasonalbot.

I can look at it tomorrow. I don't think there's anything particularly interesting that applies to Seasonal Bot, except maybe the handling of those asyncio exceptions.

**Comment by kwzrd** [comment]
@SebastiaanZ That's perfectly fine, there's no need to rush it.

**Pull request merged**
