### PR TITLE
fix the use of next() for HistoryIterator object

### LINKED ISSUE #477: Error traceback when using next/prev arrows with .help cmd
## Description

This error traceback is printed every time I click on a reaction after running the help cmd

```
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/home/hedy/.local/share/virtualenvs/seasonalbot-S5lMGbTO/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/utils/decorators.py", line 79, in guarded_listener
    return await listener(*args, **kwargs)
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/exts/halloween/candy_collection.py", line 76, in on_reaction_add
    if message.id in await self.ten_recent_msg():
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/exts/halloween/candy_collection.py", line 138, in ten_recent_msg
    msg = await next(channel.history(limit=1, before=o))
TypeError: 'HistoryIterator' object is not an iterator
```

Note that this line `Ignoring exception in on_reaction_add` is because there was an error with loading the 🗑️ emoji. (Another error is printed too, but I ignored that)

## Steps to Reproduce

1. clone code in master in set up environement
2. `pipenv run start`
3. go to discord channel and use `.help`
4. click on ➡️ 

## Expected Behaviour

no trace back

## Actual Behaviour

trace back printed

## Known Impacted Platforms

(not sure about the other platforms because I cant test on those)
- [x] Web
- [ ] Desktop
- [ ] Android App
- [x] iOS App

## Possible Solutions

not sure

## Would you like to implement a fix?

***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [x] I'd like to implement the bug fix (**but i don't really know why it's happening yet**)
- [ ] Anyone can implement the bug fix

### PR DESCRIPTION
**Pull request by hedythedev**
## Relevant Issues

closes #477 

## Description

this fixes candy_collection.py throwing
`TypeError: 'HistoryIterator' object is not an iterator` when
an arrow button is pressed after the .help command.

## Reasoning

**Before**:
```
Traceback (most recent call last):
  File "/home/hedy/.local/share/virtualenvs/seasonalbot-S5lMGbTO/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/utils/decorators.py", line 79, in guarded_listener
    return await listener(*args, **kwargs)
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/exts/halloween/candy_collection.py", line 76, in on_reaction_add
    if message.id in await self.ten_recent_msg():
  File "/mnt/c/Users/hedyh/codeproj/seasonalbot/bot/exts/halloween/candy_collection.py", line 138, in ten_recent_msg
    msg = await next(channel.history(limit=1, before=o))
TypeError: 'HistoryIterator' object is not an iterator
```

**After**:
No traceback error

Because this is an incorrect use of built-in `next()`, and `discord.iterators.HistoryIterator` has their own [`.next` method](https://github.com/Rapptz/discord.py/blob/f308f34db1b1c24178fbdb1756838064cd9e4348/discord/iterators.py#L258)

## Additional Details

~~When I tried this a few days ago, flake8 told me:
```bot/exts/halloween/candy_collection.py:138:25: B305 `.next()` is not a thing on Python 3. Use the `next()` builtin. For Python 2 compatibility, use `six.next()`.```
And i thought i needed to add a `# noqa` to it, but now I ran flake8 and it doesn't give any errors/warnings at all.~~

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
~~If dependencies have been added or updated, run `pipenv lock`?~~
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by hedythedev** [comment]
wait so the false positive of flake8 is *still* there, ok lemme fix it

**Review by MarkKoz — APPROVED** [review]
I wouldn't mind seeing `B305` added to the ignores in `tox.ini`. This warning feels like a relic of the past when Python 2 was still prevalent in people's minds.

**Comment by hedythedev** [comment]
@MarkKoz Done 👌🏻

**Comment by quanta-kt** [comment]
Hello, I am working on the same file under PR #496 and have removed those functions entirely. Please see [this commit diff](https://github.com/python-discord/seasonalbot/pull/496/commits/b83c2a9c735a9bdfd33fb1f86862ef8c50db7402)

**Comment by hedythedev** [comment]
Ok sure, I'll close this and the issue too.

**Pull request closed without merging**
