### PR TITLE
Hacktober issue finder fix - divide count by 100

### PR DESCRIPTION
**Pull request by vivax3794**
I forgot a little thing in the code " // 100" so this is a second pr. Yay.

### CODE REVIEW

**Comment by vivax3794** [comment]
I got some feedback on the embed, would it be okay if I just include it in this pr as well?

**Comment by sco1** [comment]
Yes, that's fine

**Comment by scragly** [comment]
Since it's been 5 days now since last change, I've gone ahead and merge the fix. If a refinement is needed still @vivax3794, just make a new issue/PR.

**Comment by vivax3794** [comment]
@scragly yhe, the embed. I removed 3.7 and install 3.8 so had some problem getting the bot running again. so I took a break and kinda forgot about it. sorry about that.

**Pull request merged**
