### PR TITLE
More Questions for the Trivia Quiz

### PR DESCRIPTION
**Pull request by AtieP**
6 more questions added for the quiz command on the category Evergreen. I'll add more later.
Note that only a JSON has been edited.

## Reasoning
I've added more questions because they were too few.

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [ ] If dependencies have been added or updated, run `pipenv lock`?
- [ ] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by AtieP** [comment]
I'll fix later

**Comment by Den4200** [comment]
Sure, that's fine. No need to close this though.

**Comment by ikuyarihS** [comment]
@AtieP will you have time to address the requested changes? After they have been addressed I can approve this as well

**Comment by AtieP** [comment]
@ikuyarihS Done, I addressed the requested changes.

**Review by ikuyarihS — APPROVED** [review]

**Review by Den4200 — APPROVED** [review]
Thanks @AtieP!

**Pull request merged**
