### PR TITLE
updated d.py to 1.4.1 and added voice as extra

### LINKED ISSUE #432: Update discord.py version to 1.4.1
## Description
Update the discord.py version to 1.4.1, and also put the voice extra back in

## Reasoning
It currently gets the package straight from GitHub,
https://github.com/python-discord/seasonalbot/blob/da468c51502c88c00687e2869f05a1a46c715e45/Pipfile#L10
which was necessary to allow for usage of `AllowedMentions` before it was released, but wasn't ideal. Now that the new version has been released I believe this is no longer necessary. Currently it also doesn't include the `voice` extra which is required for the `.spookysound` command, so this change should fix that.
## Proposed Implementation
Change the line in the pipfile to `discord-py = {extras = ["voice"], version = "~=1.4.1"}` and lock it. I think that's all that needs to be done.

## Would you like to implement this yourself?
- [x] I'd like to implement this feature myself
- [x] Anyone can implement this feature

(I don't mind)

### PR DESCRIPTION
**Pull request by Anubhav1603**
"Closes #432 "

uninstalled old dpy and installed new d.py with voice as extra

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by Den4200 — DISMISSED** [review]
Is there a reason we need voice features from discord.py? I can't think of any cogs that use it off the top of my head. If it's truly not needed, we shouldn't install it.

Now that we don't need git anymore, make sure to also remove its installation from the Dockerfile.

**Comment by Anubhav1603** [comment]
In [Issue 432](https://github.com/python-discord/seasonalbot/issues/432) reason is mentioned ,we require this for spooky sound command 😁

**Review by PureFunctor — APPROVED** [review]
Looks good

**Review by Akarys42 — APPROVED** [review]
Works like a charm, thanks!

**Pull request merged**
