### PR TITLE
update hacktoberstats logic for updated rules

### LINKED ISSUE #474: filter out PR labeled 'spam' in get_october_prs() for hacktoberfest
## Description
Currently it is only filtering out 'invalid' labeled PRs, we should also filter out 'spam'

## Reasoning
According to the website:
image

## Proposed Implementation
Add another `-label:` when constructing the query to the github API to filter out 'spam' labels

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

### LINKED ISSUE #491: Bot is showing reverse PRs as valid Hacktober PRs
## Description
When I do `.hackstats`, the bot thinks my reverse pull requests are also valid Hacktober PRs.
image
Even though I haven't made any PR, it says that I have made a contribution
Valid PRs
image
image

## Steps to Reproduce
Make a reverse Pull request on your fork, and type `.hackstats` in #hacktober, and you will see a contribution get addded

## Expected Behaviour

It should have shown no **valid** PRs

## Actual Behaviour

Shows a contribution, even though I haven't made any _yet_.

## Known Impacted Platforms

- [X] Web
- [ ] Desktop
- [ ] Android App
- [ ] iOS App

## Would you like to implement a fix?
***Note: For high-priority or critical bugs, fixes may be implemented by staff.***

- [X] I'd like to implement the bug fix
- [X] Anyone can implement the bug fix

### LINKED ISSUE #504: The .hackstats command also states the invalid repos
## Description
We can perhaps make the .hackstats command only show valid repos instead of total contributions.

## Reasoning
Many ppl use the discord bot to keep track of their repos and they will be in the delusion that some of their PRs were qualified, when they might have been invalid as the HacktoberFest team is closing submissions from certain large public repos, due to lack of quality.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

### PR DESCRIPTION
**Pull request by hedythedev**
## Relevant Issues

closes #474 
closes #491 
closes #504 

## Description

for hacktoberstats, prs with spam labels doesnt count as well
edit: and with updated rules, the logic must be updated

## Reasoning

**New rules**:
1. PRs before Oct 3: must not have "invalid" or "spam" labels
2. PRs after Oct 3: must be in a repo with "hacktoberfest" logic (unless it has the "hacktoberfest-accepted" label)

## Did you:

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by Akarys42 — APPROVED** [review]
Looks good to me.

**Review by gustavwilliam — CHANGES_REQUESTED** [review]
Seems like this doesn't work. Have you tested it with users who have submitted invalid PRs? I tried this out with a user who had opened 4 PRs marked as `invalid` on the cpython repo.
### Expected result
This is the result using the current version of the command. Since the PRs are marked as invalid, they aren't counted.
Screenshot 2020-10-04 at 15 46 12

### Actual result
SeasonalBot tells me that the person has contributed with 4 PRs.
Screenshot 2020-10-04 at 15 47 24

### Steps to reproduce
1. Run bot with the PR version
2. Send `.hackstats itzShiva-MarshL`

Feel free to try it out with other users who have contributed with invalid PRs as well. This was simply the first one I found.

**Comment by hedythedev** [comment]
@gustavwilliam sorry about that, it was because of the syntax, should have looked at the `+-is:draft` for reference. the latest commit should fix it, i will further test it later

**Comment by gustavwilliam** [comment]
Sure. Request another review or send a message when you think it's ready and I'll have a look.

**Comment by hedythedev** [comment]
@gustavwilliam thanks for your review, I confirmed that it works now
image

**Comment by gustavwilliam** [comment]
Sounds good. I'll have a look later today.

**Review by gustavwilliam — APPROVED** [review]
Looks good to me!

**Review by Akarys42 — CHANGES_REQUESTED** [review]
Hey, thanks for your work so far, although the rules for the hactoberfest changed again. 

Now, any PR on a repository with the `hacktoberfest` label OR a PR with the label `hacktoberfest-approved` will count, we need to update the code accordingly. 

What you should do is revert your new query parameter (sorry), and use a loop to filter out any PR that doesn’t match the requirements.

**Comment by hedythedev** [comment]
@Akarys42 the current logic will still apply for PRs before october 3, then (probably in a separate function?) find PRs after october 3 that doesn't have invalid label or spam, AND in in a repo that has a hacktoberfest topic in it (unless the PR is labeled hacktoberfest-accepted)

I should probably also implement the "pending", "mature period", etc labels, and the 14d timer (which could probably be done later).

**Comment by gustavwilliam** [comment]
> I should probably also implement the "pending", "in review", etc labels, and the 14d timer

I think we should just keep the focus on this PR to adjust it to the new rules, as fast as possible. Opening an issue for the labels mentioned above seems like a great idea to me, though! Feel free to open an issue about it.

**Comment by hedythedev** [comment]
I have tested it locally and so far it works fine for me. 

The code loops through the PRs and first checks whether the PR is made before October 3rd, and immediately continues to next iteration if so. Then it checks whether 'hacktoberfest-accepted' is one of its labels (if any), and if still doesn't apply, it proceeds to query GitHub's topic API and checks if it has the hacktoberfest topic. I have also updated the docstrings for the new rules accordingly, and the logic would obviously need to be updated for hacktoberfest next year.

I also have some suggestion to the naming of this. The code uses "shortname" for the repo owner + repo name (python-discord/seasonalbot), but I think it should be renamed to "fullname" (or just repo_name) following GitHub API's naming conventions. If you use api.github.com/repositories/search, and in the results you will find each item with a key "repo-fullname" and the value for it is "owner/repo". So maybe "shortname" isn't suitable here, let me know your opinions after you review the code and I will change it if you want me to.

**Comment by hedythedev** [comment]
Hi @MattIPv4, thanks for the flowchart. The main problem is probably because the current and previous results doesn't show the difference between 'valid' and 'waiting', it also doesnt take care of the 'PR acceptance logic', all it does is exclude invalid/spam PRs, and (for after oct 3) the ones that aren't in a hacktoberfest repo (unless hacktobefest-accepted label). @gustavwilliam has said to update the rules ASAP and do the rest (pending, in review period) in a separate issue/pr later. So I'm not really sure if this includes implementing the 'acceptance check' (as in your flowchart).

However I only found out about 'acceptance' overriding invalid/spam labels around yesterday, so I may need to update the logic on that.

**Comment by hedythedev** [comment]
**Updates:**
1. Better display of embed with different fields: 
   - In Review (not 14d yet)
   - Accepted (merged/approved/hackto-label + 14d or more)
2. When a PR is labelled invalid/spam but it is merged/approved, it will still be counted
3. Re-organised code
4. improved wording

**Review by Akarys42 — APPROVED** [review]
Thank!

**Pull request merged**
