### PR TITLE
Generic Movie Embed Generator

### PR DESCRIPTION
**Pull request by sgh304**
---
Generic Movie Embed Generator
---
Adds a generic method for generating random movie embeds.

## Pull Request Details
This abstracts out the logic from the Valentine's Day movie generation command into a util function.

This will make creating new movie generation commands easier, making them just a function call with different parameters. I've gone ahead and converted the existing `romancemovie` command to use this new function. I also plan to use this framework in a future PR to tackle issue #213.

### CODE REVIEW

**Comment by sco1** [comment]
I'm a fan of this approach with one slight tweak: rather than having a utility function, can you move this into an movie recommendation Evergreen cog so we can get movie recommendations year-round? The seasonal-specific commands should still be able to call it with their specific genre flags.

With the above in mind, it should be fine to include #213 with this PR.

**Comment by ks129** [comment]
Can I take this development over due current currently this development is pretty dead?

**Comment by SebastiaanZ** [comment]
This PR does look stale and I think it's okay for someone else to take over the development at this point.

**Comment by sco1** [comment]
More or less superseded by #350

**Pull request closed without merging**
