### PR TITLE
Renamed tox.ini to .flake8 and modified the line length rule

### PR DESCRIPTION
**Pull request by tagptroll1**
tox.ini -> .flake8
linelength rule 120 -> 100
Applied new rule to all files triggering linter.

### CODE REVIEW

**Comment by sco1** [comment]
Were the docstrings adjusted automatically? Most of the linebreaks in them are pretty harsh.

**Comment by tagptroll1** [comment]
> 
> 
> Were the docstrings adjusted automatically? Most of the linebreaks in them are pretty harsh.

Were they?  I must have skimmed the reading a bit then.  I did all the shortening by hand.

**Comment by sco1** [comment]
I'm just not really following why things like:

https://github.com/python-discord/seasonalbot/blob/20c30a5a5a87fd1f02a1d1f78a0974002aa722bc/bot/seasons/christmas/adventofcode.py#L28-L31

and 

https://github.com/python-discord/seasonalbot/blob/20c30a5a5a87fd1f02a1d1f78a0974002aa722bc/bot/seasons/christmas/adventofcode.py#L247-L256

Were adjusted the way they are, they don't seem to be anywhere close to the 100 character limit.

**Comment by sco1** [comment]
I pushed some changes rather than trying to leave review comments on everything

**Comment by sco1** [comment]
After talking it through again, the best use of time is going to be to leave the seasonalbot codebase as-is.

**Pull request closed without merging**
