### PR TITLE
handled exception of ContentTypeError at search_wikipedia

### LINKED ISSUE #452: wikipedia command bug
when u try to mention channel bot dont reply
Capture

- [x] Web
- [x] Desktop
- [x] Android App
- [x] iOS App

- [x] I'd like to implement the bug fix
- [ ] Anyone can implement the bug fix

### PR DESCRIPTION
**Pull request by Anubhav1603**
"Closes #452 "
i catched the unhandled contentError exception

bug

- [x] Join the [**Python Discord Community**](https://discord.gg/python)?
- [x] If dependencies have been added or updated, run `pipenv lock`?
- [x] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Review by Akarys42 — CHANGES_REQUESTED** [review]
Thank you the quick fix! One small thing, the return typehint of `search_wikipedia` should be `Optional[List[str]] `

**Comment by Anubhav1603** [comment]
ok

**Review by Akarys42 — APPROVED** [review]
Works like a charm. Thanks for the fix!

**Review by MrHemlock — APPROVED** [review]
Looks clean to me.

**Pull request merged**
